#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 21 14:20:58 2021

@author: johnnyseemann
"""

class Flervalgsspørsmål:
    def __init__(self, spørsmål, alt, rett_svar):
        self.spørsmål = spørsmål
        self.alt=alt
        self.rett_svar=rett_svar
        
      
    
    
    def  __str__(self):
        spørsmål= f""" {self.spørsmål} 
        1 {self.alt[0]}
        2 {self.alt[1]}
        3 {self.alt[2]}"""
        
        return spørsmål
        
    
    def sjekk_svar(self,svaret):
        if str(self.rett_svar) == str(svaret):
            print("svaret er rett")
        else: 
            print ("svaret er feil")
        
     
        
        
        
if __name__ == "__main__":
    spørsmål = "Hvor mange bein har du i kroppen?"
    alt= ["231 bein","312 bein","206 bein"]
    rett_svar = 3
    
    quiz = Flervalgsspørsmål(spørsmål, alt, rett_svar)
    print(str(quiz))
    svaret= input("svar: ")
    quiz.sjekk_svar(svaret)
    
    spørsmål = "Hva er det største organet i kroppen?"
    alt= ["Huden","hjerte","lungene"]
    rett_svar = 1
    
    quiz = Flervalgsspørsmål(spørsmål, alt, rett_svar)
    print(str(quiz))
    svaret= input("svar: ")
    quiz.sjekk_svar(svaret)
    
    